apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wazuh.fullname" . }}-api-cred
  labels:
  {{- include "wazuh.labels" . | nindent 4 }}
data:
  password: {{ required "wazuhApiCred.password is required" .Values.wazuhApiCred.password
    | b64enc | quote }}
  username: {{ required "wazuhApiCred.username is required" .Values.wazuhApiCred.username
    | b64enc | quote }}
type: Opaque
