apiVersion: v1
kind: Service
metadata:
  name: {{ include "wazuh.fullname" . }}-cluster
  labels:
    app: wazuh-manager
  {{- include "wazuh.labels" . | nindent 4 }}
spec:
  type: {{ .Values.wazuhCluster.type }}
  selector:
    app: wazuh-manager
    {{- include "wazuh.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.wazuhCluster.ports | toYaml | nindent 2 }}
