apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wazuh.fullname" . }}-cluster-key
  labels:
  {{- include "wazuh.labels" . | nindent 4 }}
data:
  key: {{ required "wazuhClusterKey.key is required" .Values.wazuhClusterKey.key
    | b64enc | quote }}
type: Opaque
