apiVersion: v1
kind: ConfigMap
metadata:
  name: indexer-conf
  labels:
  {{- include "wazuh.labels" . | nindent 4 }}
data:
  internal_users.yml: {{ .Values.indexerConf.internalUsersYml | toYaml | indent 1 }}
  opensearch.yml: {{ .Values.indexerConf.opensearchYml | toYaml | indent 1 }}

