{{- if .Values.hpa.enabled }}
{{- range $component, $config := .Values.hpa.components }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "wazuh.fullname" $ }}-{{ $component | lower }}-hpa
  labels:
    app: wazuh-{{ $component }}
    {{- include "wazuh.labels" $ | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: {{ $config.kind }}
    name: {{ include "wazuh.fullname" $ }}-{{ $component | lower }}
  minReplicas: {{ $config.minReplicas }}
  maxReplicas: {{ $config.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $config.cpuUtilization }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ $config.memoryUtilization }}
{{- end }}
{{- end }}
