apiVersion: v1
kind: Service
metadata:
  name: indexer
  labels:
    app: wazuh-indexer
  {{- include "wazuh.labels" . | nindent 4 }}
spec:
  type: {{ .Values.indexer.type }}
  selector:
    app: wazuh-indexer
    {{- include "wazuh.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.indexer.ports | toYaml | nindent 2 }}
