apiVersion: v1
kind: Secret
metadata:
  name: indexer-certs
  labels:
  {{- include "wazuh.labels" . | nindent 4 }}
data:
  admin-key.pem: |
    {{ .Files.Get (printf "%s/admin-key.pem" .Values.indexerCerts.certsPath) | b64enc }}
  admin.pem: |
    {{ .Files.Get (printf "%s/admin.pem" .Values.indexerCerts.certsPath) | b64enc }}
  dashboard-key.pem: |
    {{ .Files.Get (printf "%s/dashboard-key.pem" .Values.indexerCerts.certsPath) | b64enc }}
  dashboard.pem: |
    {{ .Files.Get (printf "%s/dashboard.pem" .Values.indexerCerts.certsPath) | b64enc }}
  filebeat-key.pem: |
    {{ .Files.Get (printf "%s/filebeat-key.pem" .Values.indexerCerts.certsPath) | b64enc }}
  filebeat.pem: |
    {{ .Files.Get (printf "%s/filebeat.pem" .Values.indexerCerts.certsPath) | b64enc }}
  node-key.pem: |
    {{ .Files.Get (printf "%s/node-key.pem" .Values.indexerCerts.certsPath) | b64enc }}
  node.pem: |
    {{ .Files.Get (printf "%s/node.pem" .Values.indexerCerts.certsPath) | b64enc }}
  root-ca.pem: |
    {{ .Files.Get (printf "%s/root-ca.pem" .Values.indexerCerts.certsPath) | b64enc }}
type: Opaque
