apiVersion: v1
kind: Secret
metadata:
  name: indexer-cred
  labels:
  {{- include "wazuh.labels" . | nindent 4 }}
data:
  password: {{ required "indexerCred.password is required" .Values.indexerCred.password
    | b64enc | quote }}
  username: {{ required "indexerCred.username is required" .Values.indexerCred.username
    | b64enc | quote }}
type: Opaque
