apiVersion: v1
kind: Secret
metadata:
  name: leena-ai-tls
  labels:
  {{- include "wazuh.labels" . | nindent 4 }}
  annotations:
    meta.helm.sh/release-name: leena-ai-tls
data:
  tls.crt: |
    {{ .Files.Get (printf "%s/tls.crt" .Values.leenaAiTls.certsPath) | b64enc }}
  tls.key: |
    {{ .Files.Get (printf "%s/tls.key" .Values.leenaAiTls.certsPath) | b64enc }}
type: kubernetes.io/tls
