apiVersion: v1
kind: Service
metadata:
  name: {{ include "wazuh.fullname" . }}-workers
  labels:
    app: wazuh-manager
  {{- include "wazuh.labels" . | nindent 4 }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
spec:
  type: {{ .Values.wazuhWorkers.type }}
  selector:
    app: wazuh-manager
    node-type: worker
    {{- include "wazuh.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.wazuhWorkers.ports | toYaml | nindent 2 }}
