apiVersion: v1
kind: Service
metadata:
  name: dashboard
  labels:
    app: wazuh-dashboard
  {{- include "wazuh.labels" . | nindent 4 }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: https
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
spec:
  type: {{ .Values.dashboard.type }}
  selector:
    app: wazuh-dashboard
    {{- include "wazuh.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.dashboard.ports | toYaml | nindent 2 }}
