apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "wazuh.fullname" . }}-manager-master
  labels:
  {{- include "wazuh.labels" . | nindent 4 }}
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  podManagementPolicy: Parallel
  replicas: {{ .Values.wazuhManagerMaster.replicas }}
  selector:
    matchLabels:
      app: wazuh-manager
      node-type: master
  serviceName: {{ include "wazuh.fullname" . }}-cluster
  template:
    metadata:
      labels:
        app: wazuh-manager
        node-type: master
        app.kubernetes.io/instance: wazuh
        app.kubernetes.io/name: wazuh
      name: wazuh-manager-master
    spec:
      containers:
      - env:
        - name: INDEXER_URL
          value: "https://indexer:9200"
        - name: INDEXER_USERNAME
          valueFrom:
            secretKeyRef:
              key: username
              name: indexer-cred
        - name: INDEXER_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: indexer-cred
        - name: FILEBEAT_SSL_VERIFICATION_MODE
          value: "full"
        - name: SSL_CERTIFICATE_AUTHORITIES
          value: "/etc/ssl/root-ca.pem"
        - name: SSL_CERTIFICATE
          value: "/etc/ssl/filebeat.pem"
        - name: SSL_KEY
          value: "/etc/ssl/filebeat.key"
        - name: API_USERNAME
          valueFrom:
            secretKeyRef:
              key: username
              name: {{ include "wazuh.fullname" . }}-api-cred
        - name: API_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: {{ include "wazuh.fullname" . }}-api-cred
        - name: WAZUH_CLUSTER_KEY
          valueFrom:
            secretKeyRef:
              key: key
              name: {{ include "wazuh.fullname" . }}-cluster-key
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}




        image: {{ .Values.wazuhManagerMaster.wazuhManager.image.repository }}:{{ .Values.wazuhManagerMaster.wazuhManager.image.tag
          | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.wazuhManagerMaster.wazuhManager.imagePullPolicy
          }}
        name: wazuh-manager
        ports:
        - containerPort: 1515
          name: registration
          protocol: TCP
        - containerPort: 1516
          name: cluster
          protocol: TCP
        - containerPort: 55000
          name: api
          protocol: TCP
        resources: {{- toYaml .Values.wazuhManagerMaster.wazuhManager.resources | nindent
          10 }}
        securityContext: {{- toYaml .Values.wazuhManagerMaster.wazuhManager.containerSecurityContext
          | nindent 10 }}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /wazuh-config-mount/etc/ossec.conf
          name: config
          readOnly: true
          subPath: master.conf
        - mountPath: /etc/ssl/root-ca.pem
          name: filebeat-certs
          readOnly: true
          subPath: root-ca.pem
        - mountPath: /etc/ssl/filebeat.pem
          name: filebeat-certs
          readOnly: true
          subPath: filebeat.pem
        - mountPath: /etc/ssl/filebeat.key
          name: filebeat-certs
          readOnly: true
          subPath: filebeat-key.pem
        - mountPath: /wazuh-config-mount/etc/authd.pass
          name: wazuh-authd-pass
          readOnly: true
          subPath: authd.pass
        - mountPath: /var/ossec/api/configuration
          name: wazuh-manager-master
          subPath: wazuh/var/ossec/api/configuration
        - mountPath: /var/ossec/etc
          name: wazuh-manager-master
          subPath: wazuh/var/ossec/etc
        - mountPath: /var/ossec/logs
          name: wazuh-manager-master
          subPath: wazuh/var/ossec/logs
        - mountPath: /var/ossec/queue
          name: wazuh-manager-master
          subPath: wazuh/var/ossec/queue
        - mountPath: /var/ossec/var/multigroups
          name: wazuh-manager-master
          subPath: wazuh/var/ossec/var/multigroups
        - mountPath: /var/ossec/integrations
          name: wazuh-manager-master
          subPath: wazuh/var/ossec/integrations
        - mountPath: /var/ossec/active-response/bin
          name: wazuh-manager-master
          subPath: wazuh/var/ossec/active-response/bin
        - mountPath: /var/ossec/agentless
          name: wazuh-manager-master
          subPath: wazuh/var/ossec/agentless
        - mountPath: /var/ossec/wodles
          name: wazuh-manager-master
          subPath: wazuh/var/ossec/wodles
        - mountPath: /etc/filebeat
          name: wazuh-manager-master
          subPath: filebeat/etc/filebeat
        - mountPath: /var/lib/filebeat
          name: wazuh-manager-master
          subPath: filebeat/var/lib/filebeat
      dnsPolicy: ClusterFirst
      nodeSelector: {{- toYaml .Values.wazuhManagerMaster.nodeSelector | nindent 8
        }}
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {{- toYaml .Values.wazuhManagerMaster.podSecurityContext | nindent
        8 }}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: {{ include "wazuh.fullname" . }}-conf
        name: config
      - name: filebeat-certs
        secret:
          defaultMode: 420
          secretName: indexer-certs
      - name: wazuh-authd-pass
        secret:
          defaultMode: 420
          secretName: {{ include "wazuh.fullname" . }}-authd-pass
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
  - metadata:
      name: wazuh-manager-master
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 50Gi
      storageClassName: wazuh-storage
      volumeMode: Filesystem
